// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDjdFRgd_vvjj90U7HpdXG9JisGqSSmYQ',
    appId: '1:892087539412:web:2de7268d65aac6c1dc8d41',
    messagingSenderId: '892087539412',
    projectId: 'short-url-project-317d0',
    authDomain: 'short-url-project-317d0.firebaseapp.com',
    storageBucket: 'short-url-project-317d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAopRDMMah7fvOQ6LDQgiOP2hpnP_ODaY4',
    appId: '1:892087539412:android:cd10016d255f5080dc8d41',
    messagingSenderId: '892087539412',
    projectId: 'short-url-project-317d0',
    storageBucket: 'short-url-project-317d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi-lEAOTEhwrOJlNGn0dt_njG02QDrBDk',
    appId: '1:892087539412:ios:fa3b9214f0c145bddc8d41',
    messagingSenderId: '892087539412',
    projectId: 'short-url-project-317d0',
    storageBucket: 'short-url-project-317d0.firebasestorage.app',
    iosBundleId: 'com.example.shortUrl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi-lEAOTEhwrOJlNGn0dt_njG02QDrBDk',
    appId: '1:892087539412:ios:fa3b9214f0c145bddc8d41',
    messagingSenderId: '892087539412',
    projectId: 'short-url-project-317d0',
    storageBucket: 'short-url-project-317d0.firebasestorage.app',
    iosBundleId: 'com.example.shortUrl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDjdFRgd_vvjj90U7HpdXG9JisGqSSmYQ',
    appId: '1:892087539412:web:f76017ded37e5446dc8d41',
    messagingSenderId: '892087539412',
    projectId: 'short-url-project-317d0',
    authDomain: 'short-url-project-317d0.firebaseapp.com',
    storageBucket: 'short-url-project-317d0.firebasestorage.app',
  );
}
